---
- name: Configuration d'un serveur Web
  hosts: servers
  gather_facts: False
  become: yes
  tasks:
    - name: Assurer la disponibilité de la connexion SSH
      ansible.builtin.wait_for:
        port: 22
        delay: 10
        timeout: 100
        search_regex: OpenSSH
        host: "{{ ansible_host | default(inventory_hostname) }}"
      vars:
        ansible_connection: local
        become: no

    - name: Mettre à jour le cache apt manuellement
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installer Nginx
      apt:
        name: nginx
        state: present

    - name: Démarrer le service Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Créer un fichier index.html avec "Hello, World!"
      copy:
        dest: /var/www/html/index.html
        content: "Hello from ansible"
        mode: '0644'
